ingredient_index:
    path:     /
    defaults: { _controller: "MarmiWildBundle:Ingredient:index" }
    methods:  GET

ingredient_show:
    path:     /{id}/show
    defaults: { _controller: "MarmiWildBundle:Ingredient:show" }
    methods:  GET

ingredient_new:
    path:     /new
    defaults: { _controller: "MarmiWildBundle:Ingredient:new" }
    methods:  [GET, POST]

ingredient_edit:
    path:     /{id}/edit
    defaults: { _controller: "MarmiWildBundle:Ingredient:edit" }
    methods:  [GET, POST]

ingredient_delete:
    path:     /{id}/delete
    defaults: { _controller: "MarmiWildBundle:Ingredient:delete" }
    methods:  DELETE
