recette_index:
    path:     /
    defaults: { _controller: "MarmiWildBundle:Recette:index" }
    methods:  GET

recette_show:
    path:     /{id}/show
    defaults: { _controller: "MarmiWildBundle:Recette:show" }
    methods:  GET

recette_new:
    path:     /new
    defaults: { _controller: "MarmiWildBundle:Recette:new" }
    methods:  [GET, POST]

recette_edit:
    path:     /{id}/edit
    defaults: { _controller: "MarmiWildBundle:Recette:edit" }
    methods:  [GET, POST]

recette_delete:
    path:     /{id}/delete
    defaults: { _controller: "MarmiWildBundle:Recette:delete" }
    methods:  DELETE
